var searchData=
[
  ['name',['name',['http://qt-project.org/doc/qt-4.8/phonon-audiooutput.html#name-prop',1,'Phonon::AudioOutput::name()'],['../classParentDefinition.html#a1c9d905235160a6a10d494c5b8240986',1,'ParentDefinition::name()']]],
  ['namefilterdetailsvisible',['nameFilterDetailsVisible',['http://qt-project.org/doc/qt-4.8/qfiledialog-obsolete.html#nameFilterDetailsVisible-prop',1,'QFileDialog']]],
  ['namefilterdisables',['nameFilterDisables',['http://qt-project.org/doc/qt-4.8/qfilesystemmodel.html#nameFilterDisables-prop',1,'QFileSystemModel']]],
  ['namespaceprocessing',['namespaceProcessing',['http://qt-project.org/doc/qt-4.8/qxmlstreamreader.html#namespaceProcessing-prop',1,'QXmlStreamReader']]],
  ['nativemenubar',['nativeMenuBar',['http://qt-project.org/doc/qt-4.8/qmenubar.html#nativeMenuBar-prop',1,'QMenuBar']]],
  ['navigationbarvisible',['navigationBarVisible',['http://qt-project.org/doc/qt-4.8/qcalendarwidget.html#navigationBarVisible-prop',1,'QCalendarWidget']]],
  ['networkaccessible',['networkAccessible',['http://qt-project.org/doc/qt-4.8/qnetworkaccessmanager.html#networkAccessible-prop',1,'QNetworkAccessManager']]],
  ['newline',['newLine',['http://qt-project.org/doc/qt-4.8/q3dockwindow.html#newLine-prop',1,'Q3DockWindow']]],
  ['normalgeometry',['normalGeometry',['http://qt-project.org/doc/qt-4.8/qwidget.html#normalGeometry-prop',1,'QWidget']]],
  ['notation',['notation',['http://qt-project.org/doc/qt-4.8/qdoublevalidator.html#notation-prop',1,'QDoubleValidator']]],
  ['notchesvisible',['notchesVisible',['http://qt-project.org/doc/qt-4.8/qdial.html#notchesVisible-prop',1,'QDial']]],
  ['notchsize',['notchSize',['http://qt-project.org/doc/qt-4.8/qdial.html#notchSize-prop',1,'QDial']]],
  ['notchtarget',['notchTarget',['http://qt-project.org/doc/qt-4.8/qdial.html#notchTarget-prop',1,'QDial']]],
  ['nulltext',['nullText',['http://qt-project.org/doc/qt-4.8/q3datatable.html#nullText-prop',1,'Q3DataTable']]],
  ['numcols',['numCols',['http://qt-project.org/doc/qt-4.8/q3datatable.html#numCols-prop',1,'Q3DataTable::numCols()'],['http://qt-project.org/doc/qt-4.8/q3table.html#numCols-prop',1,'Q3Table::numCols()'],['http://qt-project.org/doc/qt-4.8/q3gridview.html#numCols-prop',1,'Q3GridView::numCols()']]],
  ['numcolumns',['numColumns',['http://qt-project.org/doc/qt-4.8/q3listbox.html#numColumns-prop',1,'Q3ListBox']]],
  ['numdigits',['numDigits',['http://qt-project.org/doc/qt-4.8/qlcdnumber.html#numDigits-prop',1,'QLCDNumber']]],
  ['numitemsvisible',['numItemsVisible',['http://qt-project.org/doc/qt-4.8/q3listbox.html#numItemsVisible-prop',1,'Q3ListBox']]],
  ['numlines',['numLines',['http://qt-project.org/doc/qt-4.8/q3multilineedit.html#numLines-prop',1,'Q3MultiLineEdit']]],
  ['numrows',['numRows',['http://qt-project.org/doc/qt-4.8/q3datatable.html#numRows-prop',1,'Q3DataTable::numRows()'],['http://qt-project.org/doc/qt-4.8/q3table.html#numRows-prop',1,'Q3Table::numRows()'],['http://qt-project.org/doc/qt-4.8/q3gridview.html#numRows-prop',1,'Q3GridView::numRows()'],['http://qt-project.org/doc/qt-4.8/q3listbox.html#numRows-prop',1,'Q3ListBox::numRows()']]],
  ['numselections',['numSelections',['http://qt-project.org/doc/qt-4.8/q3table.html#numSelections-prop',1,'Q3Table']]]
];
